/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rmiclient;

import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import remoteapp.InterfaceCalc;
import remoteapp.PhanSo;
/**
 *
 * @author Admin
 */
public class FormRMIClient extends javax.swing.JFrame {

    /**
     * Creates new form FormRMIClient
     */
    public FormRMIClient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDiaChi = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        btnThoat = new javax.swing.JButton();
        lblSo1 = new javax.swing.JLabel();
        txtSo1 = new javax.swing.JTextField();
        lblSo2 = new javax.swing.JLabel();
        txtSo2 = new javax.swing.JTextField();
        lblKetQua = new javax.swing.JLabel();
        txtKetQua = new javax.swing.JTextField();
        lblTuA = new javax.swing.JLabel();
        txtTuA = new javax.swing.JTextField();
        lblTuB = new javax.swing.JLabel();
        txtTuB = new javax.swing.JTextField();
        lblMauA = new javax.swing.JLabel();
        txtMauA = new javax.swing.JTextField();
        lblMauB = new javax.swing.JLabel();
        txtMauB = new javax.swing.JTextField();
        btnPlusNumber = new javax.swing.JButton();
        btnPlusFraction = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblDiaChi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDiaChi.setText("Địa chỉ server");

        txtDiaChi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        btnThoat.setBackground(java.awt.SystemColor.activeCaption);
        btnThoat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        lblSo1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSo1.setText("Số 1");

        txtSo1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        lblSo2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSo2.setText("Số 2");

        txtSo2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        lblKetQua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblKetQua.setText("Kết quả");

        txtKetQua.setBackground(java.awt.SystemColor.activeCaption);
        txtKetQua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        lblTuA.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTuA.setText("Tử số a");

        txtTuA.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        lblTuB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTuB.setText("Tử số b");

        txtTuB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        lblMauA.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMauA.setText("Mẫu số a");

        txtMauA.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        lblMauB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMauB.setText("Mẫu số b");

        txtMauB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        btnPlusNumber.setBackground(java.awt.SystemColor.activeCaption);
        btnPlusNumber.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPlusNumber.setText("+");
        btnPlusNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlusNumberActionPerformed(evt);
            }
        });

        btnPlusFraction.setBackground(java.awt.SystemColor.activeCaption);
        btnPlusFraction.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPlusFraction.setText("+");
        btnPlusFraction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlusFractionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblKetQua, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtKetQua, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSo2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtSo2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblSo1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtSo1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(110, 110, 110)
                        .addComponent(btnPlusNumber))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTuA, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtTuA, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblMauA, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtMauA, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTuB, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtTuB, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPlusFraction)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblMauB, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtMauB, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(80, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThoat)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiaChi)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSo1)
                            .addComponent(txtSo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSo2)
                            .addComponent(txtSo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnPlusNumber)
                        .addGap(38, 38, 38)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKetQua)
                    .addComponent(txtKetQua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTuA)
                    .addComponent(txtTuA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMauA)
                    .addComponent(txtMauA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTuB)
                    .addComponent(txtTuB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMauB)
                    .addComponent(txtMauB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnThoat)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPlusFraction)
                        .addContainerGap(16, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlusNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlusNumberActionPerformed
        try {
            String diaChi = this.txtDiaChi.getText();
            Registry r = LocateRegistry.getRegistry(diaChi, 3456);
            InterfaceCalc ic = (InterfaceCalc) r.lookup("rmiCalc");
            int so1 = Integer.valueOf(this.txtSo1.getText());
            int so2 = Integer.valueOf(this.txtSo2.getText());
            int c = ic.sum(so1, so2);
            this.txtKetQua.setText(String.valueOf(c));
        } catch(Exception ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_btnPlusNumberActionPerformed

    private void btnPlusFractionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlusFractionActionPerformed
        try {
            String diaChi = this.txtDiaChi.getText();
            Registry r = LocateRegistry.getRegistry(diaChi, 3456);
            InterfaceCalc ic = (InterfaceCalc) r.lookup("rmiCalc");
            PhanSo a = new PhanSo(Integer.valueOf(this.txtTuA.getText()), Integer.valueOf(this.txtTuA.getText()));
            PhanSo b = new PhanSo(Integer.valueOf(this.txtTuB.getText()), Integer.valueOf(this.txtTuB.getText()));
            PhanSo c = ic.sum(a, b);
            this.txtKetQua.setText(String.valueOf(c.getTu()) + "/" + c.getMau());
        } catch(Exception ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_btnPlusFractionActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        System.exit(1);
    }//GEN-LAST:event_btnThoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormRMIClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormRMIClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormRMIClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormRMIClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormRMIClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPlusFraction;
    private javax.swing.JButton btnPlusNumber;
    private javax.swing.JButton btnThoat;
    private javax.swing.JLabel lblDiaChi;
    private javax.swing.JLabel lblKetQua;
    private javax.swing.JLabel lblMauA;
    private javax.swing.JLabel lblMauB;
    private javax.swing.JLabel lblSo1;
    private javax.swing.JLabel lblSo2;
    private javax.swing.JLabel lblTuA;
    private javax.swing.JLabel lblTuB;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtKetQua;
    private javax.swing.JTextField txtMauA;
    private javax.swing.JTextField txtMauB;
    private javax.swing.JTextField txtSo1;
    private javax.swing.JTextField txtSo2;
    private javax.swing.JTextField txtTuA;
    private javax.swing.JTextField txtTuB;
    // End of variables declaration//GEN-END:variables
}
