/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package buoi3;

/**
 *
 * @author Hieu Pham
 */
public class InetAddress extends javax.swing.JFrame {

    static InetAddress getByName(String text) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * Creates new form InetAddress
     */
    public InetAddress() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuBarSystem = new javax.swing.JMenu();
        jMenuFunction = new javax.swing.JMenu();
        jMenuItemCheckIp = new javax.swing.JMenuItem();
        jMenuItemFindIp = new javax.swing.JMenuItem();
        jMenuItemFindDomain = new javax.swing.JMenuItem();
        jMenuItemFindIpLocal = new javax.swing.JMenuItem();
        jMenuItemCheckIP = new javax.swing.JMenuItem();
        jMenuItemCheck2Domain = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuBarSystem.setText("Hệ thống");
        jMenuBar1.add(jMenuBarSystem);

        jMenuFunction.setText("Chức năng");

        jMenuItemCheckIp.setText("Kiểm tra IP");
        jMenuItemCheckIp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCheckIpActionPerformed(evt);
            }
        });
        jMenuFunction.add(jMenuItemCheckIp);

        jMenuItemFindIp.setText("Tìm IP của tên miền");
        jMenuItemFindIp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFindIpActionPerformed(evt);
            }
        });
        jMenuFunction.add(jMenuItemFindIp);

        jMenuItemFindDomain.setText("Tìm tên miền của IP");
        jMenuItemFindDomain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFindDomainActionPerformed(evt);
            }
        });
        jMenuFunction.add(jMenuItemFindDomain);

        jMenuItemFindIpLocal.setText("Tìm IP của máy cục bộ");
        jMenuItemFindIpLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFindIpLocalActionPerformed(evt);
            }
        });
        jMenuFunction.add(jMenuItemFindIpLocal);

        jMenuItemCheckIP.setText("Kiểm tra IP");
        jMenuItemCheckIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCheckIPActionPerformed(evt);
            }
        });
        jMenuFunction.add(jMenuItemCheckIP);

        jMenuItemCheck2Domain.setText("Kiểm tra 2 tên miền");
        jMenuItemCheck2Domain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCheck2DomainActionPerformed(evt);
            }
        });
        jMenuFunction.add(jMenuItemCheck2Domain);

        jMenuBar1.add(jMenuFunction);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 504, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCheckIpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCheckIpActionPerformed
        // TODO add your handling code here:
        CheckIP form = new CheckIP();
        form.setVisible(true);
    }//GEN-LAST:event_jMenuItemCheckIpActionPerformed

    private void jMenuItemFindIpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFindIpActionPerformed
        // TODO add your handling code here:
        FindIp form = new FindIp();
        form.setVisible(true);
    }//GEN-LAST:event_jMenuItemFindIpActionPerformed

    private void jMenuItemFindDomainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFindDomainActionPerformed
        // TODO add your handling code here:
        FindDomain form = new FindDomain();
        form.setVisible(true);
    }//GEN-LAST:event_jMenuItemFindDomainActionPerformed

    private void jMenuItemFindIpLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFindIpLocalActionPerformed
        // TODO add your handling code here:
        CheckIpLocal form = new CheckIpLocal();
        form.setVisible(true);
    }//GEN-LAST:event_jMenuItemFindIpLocalActionPerformed

    private void jMenuItemCheckIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCheckIPActionPerformed
        // TODO add your handling code here:
        CheckIP_LoopBack_Multicast form = new CheckIP_LoopBack_Multicast();
        form.setVisible(true);
    }//GEN-LAST:event_jMenuItemCheckIPActionPerformed

    private void jMenuItemCheck2DomainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCheck2DomainActionPerformed
        // TODO add your handling code here:
        Check2Domain form = new Check2Domain();
        form.setVisible(true);
    }//GEN-LAST:event_jMenuItemCheck2DomainActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InetAddress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InetAddress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InetAddress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InetAddress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InetAddress().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuBarSystem;
    private javax.swing.JMenu jMenuFunction;
    private javax.swing.JMenuItem jMenuItemCheck2Domain;
    private javax.swing.JMenuItem jMenuItemCheckIP;
    private javax.swing.JMenuItem jMenuItemCheckIp;
    private javax.swing.JMenuItem jMenuItemFindDomain;
    private javax.swing.JMenuItem jMenuItemFindIp;
    private javax.swing.JMenuItem jMenuItemFindIpLocal;
    // End of variables declaration//GEN-END:variables
}
